api_platform:
    title: ApiPlatformBoilerplate
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: true # To enable or disable pagination for all resource collections by default.
            client_enabled: true # To allow the client to enable or disable the pagination.
            enabled_parameter_name: 'pagination' # The name of the query parameter to enable or disable pagination.
            client_items_per_page: true # To allow the client to set the number of items per page.
            items_per_page: 10 # The default number of items per page.
            items_per_page_parameter_name: 'perPage' # The name of the query parameter to set the number of items per page.
